# Generated by Django 4.2 on 2023-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("responsibilities", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Júnior"),
                            ("PLENO", "Pleno"),
                            ("SENIOR", "Sênior"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
