# Generated by Django 4.2 on 2023-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_skill_job_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="level",
            field=models.CharField(
                choices=[
                    ("Júnior", "Júnior"),
                    ("Pleno", "Pleno"),
                    ("Sênior", "Sênior"),
                ],
                max_length=10,
            ),
        ),
    ]
